const mongoose = require("mongoose");
const dotenv = require("dotenv");
const path = require("path");

// Load env vars
dotenv.config({ path: path.join(__dirname, "../.env") });

const School = require("../models/school.model");
const SchoolArea = require("../models/schoolArea.model");
const connectDB = require("../config/db");

const schoolsData = [
  {
    name: "University of Lagos",
    abbr: "UNILAG",
    state: "Lagos",
    areas: [
      "New Hall",
      "Moremi Hall",
      "Mariere Hall",
      "Jaja Hall",
      "Honours Hall",
      "Faculty of Science",
      "Faculty of Arts",
      "Main Auditorium",
      "Senate Building",
      "Main Gate",
      "Second Gate",
    ],
  },
  {
    name: "Ladoke Akintola University of Technology",
    abbr: "LAUTECH",
    state: "Oyo",
    areas: [
      "Under G",
      "Adenike",
      "Yoaco",
      "Stadium Road",
      "General",
      "Aroje",
      "Ogbomosho High School Area",
      "School Gate",
      "College of Health Sciences",
      "Back Gate",
    ],
  },
  {
    name: "Federal University of Technology, Owerri",
    abbr: "FUTO",
    state: "Imo",
    areas: [
      "Eziobodo",
      "Ihiagwa",
      "Umuchima",
      "Hostel A",
      "Hostel B",
      "Hostel C",
      "NDDC Hostel",
      "School of Science (SOS)",
      "SEET Roundabout",
      "Senate Building",
      "FUTO Back Gate",
    ],
  },
  {
    name: "University of Nigeria, Nsukka",
    abbr: "UNN",
    state: "Enugu",
    areas: [
      "Franco Hostel",
      "Mary Slessor Hall",
      "Awolowo Hall",
      "Eni Njoku Hall",
      "Isa Kaita Hall",
      "Freedom Square",
      "Ekpo Ref",
      "SUB",
      "Stadium",
      "Hilltop",
      "Behind Flat",
    ],
  },
  {
    name: "Obafemi Awolowo University",
    abbr: "OAU",
    state: "Osun",
    areas: [
      "Awolowo Hall",
      "Angola Hall",
      "Moremi Hall",
      "Mozambique Hall",
      "Akintola Hall",
      "ETF Hall",
      "Amphitheatre",
      "Spider Building",
      "SUB",
      "Motion Ground",
      "Main Gate",
    ],
  },
  {
    name: "University of Benin",
    abbr: "UNIBEN",
    state: "Edo",
    areas: [
      "Hall 1",
      "Hall 2",
      "Hall 3",
      "Hall 4",
      "Hall 6",
      "Hall 7",
      "June 12",
      "Main Gate",
      "Maingate",
      "Ekosodin",
      "BDPA",
    ],
  },
  {
    name: "University of Ilorin",
    abbr: "UNILORIN",
    state: "Kwara",
    areas: [
      "Sub",
      "Walkway",
      "Park",
      "Lecture Theatre 1",
      "Lecture Theatre 2",
      "New Hostel",
      "Old Hostel",
      "Main Gate",
      "School Clinic",
      "Sanango",
      "Tanke",
    ],
  },
  {
    name: "Lagos State University",
    abbr: "LASU",
    state: "Lagos",
    areas: [
      "Ojo Campus",
      "Epe Campus",
      "Ikeja Campus",
      "Main Gate",
      "Iyana Iba",
      "PPL",
      "Okokomaiko",
      "Faculty of Law",
      "MBA",
      "New Senate Building",
    ],
  },
  {
    name: "Ahmadu Bello University",
    abbr: "ABU",
    state: "Kaduna",
    areas: [
      "Main Campus (Samaru)",
      "Kongo Campus",
      "Suleiman Hall",
      "Amina Hall",
      "Ribadu Hall",
      "Alexander Hall",
      "North Gate",
      "Main Gate",
      "Senate Building",
      "Area A",
    ],
  },
  {
    name: "University of Ibadan",
    abbr: "UI",
    state: "Oyo",
    areas: [
      "Kuti Hall",
      "Sultan Bello Hall",
      "Queen Idia Hall",
      "Awolowo Hall",
      "Indy Hall",
      "Zik Hall",
      "Mellanby Hall",
      "Tedder Hall",
      "SUB",
      "Tech Road",
      "Main Gate",
    ],
  },
  {
    name: "Covenant University",
    abbr: "CU",
    state: "Ogun",
    areas: [
      "Peter Hall",
      "Paul Hall",
      "Joseph Hall",
      "Esther Hall",
      "Mary Hall",
      "Deborah Hall",
      "Cafeteria 1",
      "Cafeteria 2",
      "CST",
      "ALDC",
      "Chapel",
    ],
  },
  {
    name: "University of Port Harcourt",
    abbr: "UNIPORT",
    state: "Rivers",
    areas: [
      "Abuja Campus",
      "Choba Campus",
      "Delta Park",
      "Gambhing",
      "Back of Stadium",
      "Clinical Hostel",
      "Dan Etete Hall",
      "Nelson Mandela Hall",
      "Claude Ake Hall",
      "Main Gate",
    ],
  },
  {
    name: "Federal University of Technology, Akure",
    abbr: "FUTA",
    state: "Ondo",
    areas: [
      "Obanla",
      "Obakekere",
      "South Gate",
      "North Gate",
      "Jibowu Hall",
      "Akindeko Hall",
      "Adeniyifasuhan Hall",
      "ETF Hostel",
      "School Farm",
      "SUB",
    ],
  },
  {
    name: "University of Abuja",
    abbr: "UNIABUJA",
    state: "FCT",
    areas: [
      "Main Campus",
      "Mini Campus",
      "Gwagwalada",
      "Girls Hostel",
      "Boys Hostel",
      "FCDA Quarters",
      "Faculty of Law",
      "Giri",
      "School Gate",
      "Senate Building",
    ],
  },
  {
    name: "Nnamdi Azikiwe University",
    abbr: "UNIZIK",
    state: "Anambra",
    areas: [
      "Ifite",
      "Temp Site",
      "Perm Site",
      "School Hostel",
      "Faculty of Engineering",
      "Science Village",
      "Admin Block",
      "Bank Road",
      "Miracle Centre",
      "Main Gate",
    ],
  },
  {
    name: "Babcock University",
    abbr: "BABCOCK",
    state: "Ogun",
    areas: [
      "Winslow Hall",
      "Gideon Troopers",
      "Neal Wilson",
      "Welch Hall",
      "Nelson Mandela",
      "Bethel Splendor",
      "Havilah Gold",
      "Queen Esther",
      "Platinum Hall",
      "Main Gate",
    ],
  },
  {
    name: "Landmark University",
    abbr: "LANDMARK",
    state: "Kwara",
    areas: [
      "Male Hostel 1",
      "Male Hostel 2",
      "Female Hostel 1",
      "Female Hostel 2",
      "Cafeteria",
      "College of Science",
      "College of Engineering",
      "Farm Road",
      "Main Gate",
      "Chapel",
    ],
  },
  {
    name: "Federal University of Agriculture, Abeokuta",
    abbr: "FUNAAB",
    state: "Ogun",
    areas: [
      "Camp Area",
      "School Hostel",
      "Iyana Camp",
      "Alabata",
      "Harmony Hostel",
      "Titanic Hostel",
      "Mandela Hostel",
      "Main Gate",
      "Motion Ground",
      "Ceremonial Building",
    ],
  },
  {
    name: "Bayero University Kano",
    abbr: "BUK",
    state: "Kano",
    areas: [
      "New Site",
      "Old Site",
      "Nana Hall",
      "Ramat Hall",
      "El-Kanemi Hall",
      "Dangote Hostel",
      "Faculty of Engineering",
      "Main Library",
      "School Clinic",
      "Staff Quarters",
    ],
  },
  {
    name: "University of Calabar",
    abbr: "UNICAL",
    state: "Cross River",
    areas: [
      "Malabor",
      "Hall 2",
      "Hall 4",
      "Hall 5",
      "Hall 6",
      "Hall 8",
      "Goldie Gate",
      "Main Gate",
      "Library Complex",
      "New Arts Theatre",
    ],
  },
  {
    name: "University of Jos",
    abbr: "UNIJOS",
    state: "Plateau",
    areas: [
      "Bauchi Road Campus",
      "Naraguta Campus",
      "Village Hostel",
      "Abuja Hostel",
      "Students Centre",
      "Main Library",
      "Faculty of Medical Sciences",
      "Permanent Site",
      "Senior Staff Quarters",
      "Farin Gada",
    ],
  },
  {
    name: "Ekiti State University",
    abbr: "EKSU",
    state: "Ekiti",
    areas: [
      "Ivoroko",
      "Osekita",
      "Satellite Hostel",
      "Main Gate",
      "School Gate",
      "3000 Capacity Hall",
      "Faculty of Education",
      "Faculty of Science",
      "New Garage",
      "Abere",
    ],
  },
  {
    name: "Olabisi Onabanjo University",
    abbr: "OOU",
    state: "Ogun",
    areas: [
      "Ago Iwoye",
      "Perm Site",
      "Mini Campus",
      "Annex",
      "Ayegbami",
      "Oru",
      "Ilaporu",
      "School Hostel",
      "Garri Procession",
      "Main Gate",
    ],
  },
  {
    name: "Abia State University",
    abbr: "ABSU",
    state: "Abia",
    areas: [
      "Uturu",
      "School Hostel",
      "Student Affairs",
      "Faculty of Law",
      "Medical Hostel",
      "Lecture East",
      "Lecture West",
      "Main Gate",
      "Okigwe Road",
      "Roundabout",
    ],
  },
  {
    name: "Rivers State University",
    abbr: "RSU",
    state: "Rivers",
    areas: [
      "Nkpolu",
      "Main Gate",
      "Back Gate",
      "Hostel A",
      "Hostel B",
      "Hostel C",
      "NDDC Hostel",
      "Tech Roundabout",
      "Amphitheatre",
      "Shopping Complex",
    ],
  },
  {
    name: "Delta State University",
    abbr: "DELSU",
    state: "Delta",
    areas: [
      "Site 1",
      "Site 2",
      "Site 3",
      "Main Gate",
      "Abraka",
      "Medical Hostel",
      "Ethiope Hall",
      "Canon Hall",
      "NDDC Hostel",
      "Senate Building",
    ],
  },
  {
    name: "Federal University Oye-Ekiti",
    abbr: "FUOYE",
    state: "Ekiti",
    areas: [
      "Oye Campus",
      "Ikole Campus",
      "Ayegbaju",
      "School Hostel",
      "Falcons",
      "Adebayo",
      "Main Gate",
      "Phase 1",
      "Phase 2",
      "Green House",
    ],
  },
  {
    name: "Afe Babalola University",
    abbr: "ABUAD",
    state: "Ekiti",
    areas: [
      "Male Hostel",
      "Female Hostel",
      "Talent Discovery Centre",
      "Cafeteria",
      "College of Law",
      "College of Engineering",
      "Multi-System Hospital",
      "Staff Quarters",
      "Main Gate",
      "Farm",
    ],
  },
  {
    name: "Bells University",
    abbr: "BELLS",
    state: "Ogun",
    areas: [
      "Silver Hall",
      "Bronze Hall",
      "Gold Hall",
      "Marquee",
      "Rec Centre",
      "Main Gate",
      "College of Engineering",
      "COLMAN",
      "Food Court",
      "Chapel",
    ],
  },
  {
    name: "Bowen University",
    abbr: "BOWEN",
    state: "Osun",
    areas: [
      "New Hostel",
      "Ajegunle",
      "Chapel",
      "Admin Block",
      "Library",
      "BUPAF",
      "Main Gate",
      "Male Hostel",
      "Female Hostel",
      "Staff Quarters",
    ],
  },
];

const seedSchools = async () => {
  try {
    await connectDB();
    console.log("Connected to database...");

    // Clear existing data
    await School.deleteMany({});
    await SchoolArea.deleteMany({});
    console.log("Cleared existing schools and areas.");

    for (const schoolData of schoolsData) {
      // Create School
      const school = await School.create({
        name: schoolData.name,
        abbr: schoolData.abbr,
        state: schoolData.state,
      });
      console.log(`Created school: ${school.name}`);

      // Create School Areas
      const areasToCreate = schoolData.areas.map((areaName) => ({
        name: areaName,
        schoolName: school.name,
        location: {
          type: "Point",
          coordinates: [0, 0], // Default coordinates, update real ones if needed later
        },
      }));

      await SchoolArea.insertMany(areasToCreate);
      console.log(`  - Added ${areasToCreate.length} areas for ${school.abbr}`);
    }

    console.log("\nSeeding completed successfully!");
    process.exit(0);
  } catch (error) {
    console.error("Error seeding database:", error);
    process.exit(1);
  }
};

seedSchools();
