module.exports = {
  free: {
    name: "Free",
    slug: "free",
    price: 0,
    limits: {
      productsPerPost: 4,
      postsPer12Hours: 2,
    },
    features: {
      priorityFeed: false,
      badge: null,
      analytics: ["views"],
      messaging: false,
      featuredProducts: false,
      homepageSpotlight: false,
    },
  },
  boost: {
    name: "Vendora Boost",
    slug: "vendora-boost",
    price: 750,
    limits: {
      productsPerPost: 6,
      postsPer12Hours: 4,
    },
    features: {
      priorityFeed: true,
      badge: "Boosted Vendor",
      increasedImpressions: true,
      priorityLocationSearch: true,
      analytics: ["views", "messages_initiated"],
      messaging: false,
      featuredProducts: false,
      homepageSpotlight: false,
    },
  },
  pro: {
    name: "Vendora Pro",
    slug: "vendora-pro",
    price: 1500,
    limits: {
      productsPerPost: 10,
      postsPer12Hours: 6,
    },
    features: {
      priorityFeed: true,
      badge: "Orange",
      analytics: ["views", "saves", "clicks"],
      messaging: true,
      featuredProducts: true,
      homepageSpotlight: false,
      customBranding: true,
      pinPost: true,
    },
  },
  max: {
    name: "Vendora Max",
    slug: "vendora-max",
    price: 3000,
    limits: {
      productsPerPost: 20,
      postsPer12Hours: 20,
    },
    features: {
      priorityFeed: true,
      badge: "Verification Badge",
      analytics: ["views", "saves", "messages", "conversion"],
      messaging: true,
      featuredProducts: true,
      homepageSpotlight: true,
      advancedAnalytics: true,
      prioritySupport: true,
      postScheduling: true,
      profileSuggestion: true,
    },
  },
};
